//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission_Details
    {
        public long Admission_Details_Id { get; set; }
        public Nullable<long> Type_Of_Admission_Id { get; set; }
        public Nullable<long> Admhour { get; set; }
        public string AdmSource { get; set; }
        public Nullable<long> Type_of_Bill { get; set; }
        public Nullable<long> Dischargehour { get; set; }
        public Nullable<long> Discharge_status_Id { get; set; }
        public Nullable<long> Claim_No { get; set; }
        public Nullable<long> Practice_code { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
