//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Batch_Exceptions
    {
        public int ID { get; set; }
        public string PracticeCode { get; set; }
        public string Exception { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> Batch_ID { get; set; }
        public Nullable<long> Claim_ID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool deleted { get; set; }
    }
}
