//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Overpayment
    {
        public long id { get; set; }
        public Nullable<long> Claim_No { get; set; }
        public Nullable<decimal> Insurance_over_paid { get; set; }
        public Nullable<decimal> Patient_credit_balance { get; set; }
        public Nullable<decimal> Total_Responsibility { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTimeOffset> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTimeOffset> Modified_date { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
