//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSI_Batch_Response
    {
        public int Id { get; set; }
        public Nullable<int> Batch_Id { get; set; }
        public string Batch_Name { get; set; }
        public string File_Path { get; set; }
        public Nullable<System.DateTime> Downloading_Date { get; set; }
        public Nullable<int> Practice_Id { get; set; }
        public string Claim_Number { get; set; }
        public Nullable<int> Payer_Id { get; set; }
        public string String_277 { get; set; }
        public string Downloading_Status { get; set; }
    }
}
