//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomEdits_Test
    {
        public int id { get; set; }
        public Nullable<long> RequestedUserID { get; set; }
        public string RequestedUserName { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string RequestedColumnName { get; set; }
        public string RequestedCondition { get; set; }
    }
}
