//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom_Edits
    {
        public int ID { get; set; }
        public string Practice_Code { get; set; }
        public string Column_Name { get; set; }
        public string Operator { get; set; }
        public string Custom_Values { get; set; }
        public string UserErrorMassage { get; set; }
        public string ColumnName { get; set; }
        public string Column_Operator { get; set; }
        public string CustomValues { get; set; }
        public string ErrorMessage { get; set; }
    }
}
