//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edits_jinnah
    {
        public long Edit_id { get; set; }
        public Nullable<long> practice_code { get; set; }
        public long Gc_id { get; set; }
        public string Entity_1 { get; set; }
        public string Field_1 { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public string Entity_2 { get; set; }
        public string Field_2 { get; set; }
        public string Condition { get; set; }
        public string Error_Message { get; set; }
    }
}
