//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edit
    {
        public int id { get; set; }
        public string procedureCode { get; set; }
        public string isActive { get; set; }
        public string editGroup { get; set; }
        public string POS { get; set; }
    }
}
