//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERA_PLB_CODE
    {
        public long S_NO { get; set; }
        public Nullable<long> ERAID { get; set; }
        public string CLAIM_NO { get; set; }
        public string CODE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
