//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eraclaiminfo_impt
    {
        public int ERAID { get; set; }
        public int LOOPID { get; set; }
        public int PATIENTACCOUNTNUMBER { get; set; }
        public string CLAIMPROCESSEDAS { get; set; }
        public string TOTALCHARGE { get; set; }
        public string CLAIMPAYMENT { get; set; }
        public string CLAIMPATIENTRESP { get; set; }
        public string ICN { get; set; }
        public string PATLASTNAME { get; set; }
        public string INSUREDLNAME { get; set; }
        public string PATFIRSTNAME { get; set; }
        public string INSUREDFNAME { get; set; }
        public string PATMI { get; set; }
        public string INSUREDMI { get; set; }
        public string MEMBERIDENTIFICATION { get; set; }
        public string INSUREDMEMBERIDENTIFICATION { get; set; }
        public System.DateTime STDATE { get; set; }
        public System.DateTime STENDDATE { get; set; }
        public string PROCCODE { get; set; }
        public string BILLEDAMOUNT { get; set; }
        public string PROVIDERPAID { get; set; }
        public System.DateTime SVCSTDT { get; set; }
        public System.DateTime SVCEDT { get; set; }
        public string ADJCODE1 { get; set; }
        public string ADJCODE2 { get; set; }
        public string ADJAMT1 { get; set; }
        public string ADJCODE3 { get; set; }
        public string ADJAMT2 { get; set; }
        public string PRESP { get; set; }
        public string PRTYPE { get; set; }
        public string PRESAMT { get; set; }
        public string ALLOWEDAMT { get; set; }
        public string POSTED { get; set; }
        public System.DateTime posteddate { get; set; }
    }
}
