//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalPractices_Reporting
    {
        public int id { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public string Practice_Name { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
