//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File277CA
    {
        public int id { get; set; }
        public string FilePathName { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> FileEntry { get; set; }
        public string LogFileCreated { get; set; }
        public string LogFileName { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalParse { get; set; }
        public Nullable<int> FailedParse { get; set; }
        public Nullable<int> Provider_Level_Rejection { get; set; }
    }
}
