//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Functional_Group_Rejection_Response
    {
        public int id { get; set; }
        public string segment { get; set; }
        public string code { get; set; }
        public string description { get; set; }
    }
}
