//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUARANTORS_MAPPING_1011004
    {
        public long GUARANTOR_CODE { get; set; }
        public string GUARANT_LNAME { get; set; }
        public string GUARANT_FNAME { get; set; }
        public string GUARANT_MI { get; set; }
        public string GUARANT_ADDRESS { get; set; }
        public string GUARANT_CITY { get; set; }
        public string GUARANT_STATE { get; set; }
        public string GUARANT_ZIP { get; set; }
        public Nullable<System.DateTime> GUARANT_DOB { get; set; }
        public string GUARANT_SSN { get; set; }
        public string GUARANT_GENDER { get; set; }
        public string GUARANT_HOME_PHONE { get; set; }
        public int DELETED { get; set; }
        public int CREATED_BY { get; set; }
        public System.DateTimeOffset CREATED_DATE { get; set; }
        public string GUARANT_TYPE { get; set; }
        public Nullable<int> RESPONSIBLEPARTYFID { get; set; }
        public Nullable<int> CHARTID { get; set; }
    }
}
