//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GUARANTORSRAW_1011004
    {
        public Nullable<int> patient_uid { get; set; }
        public Nullable<int> RESPONSIBLEPARTYFID { get; set; }
        public Nullable<int> LicenseKey { get; set; }
        public Nullable<int> ResponsibleParty_UID { get; set; }
        public string Employer { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string AcctType { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string SSN { get; set; }
        public Nullable<bool> SendSTMT { get; set; }
        public Nullable<short> STMTBillingCycle { get; set; }
        public Nullable<bool> FinanceCharge { get; set; }
        public string STMTFormatName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeExtension { get; set; }
        public string Fax { get; set; }
        public string Cell { get; set; }
        public string Pager { get; set; }
        public string HomePhone { get; set; }
        public string Other { get; set; }
        public string PhoneType { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Display { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
        public string GUARANT_TYPE { get; set; }
    }
}
