//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HASHHASHA
    {
        public long CLAIM_NO { get; set; }
        public Nullable<decimal> AMT_DUE { get; set; }
        public string PAT_STATUS { get; set; }
        public string PRI_STATUS { get; set; }
        public string SEC_STATUS { get; set; }
        public string OTH_STATUS { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
