//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Month_end_payments_adjustments
    {
        public long claim_no { get; set; }
        public Nullable<long> patient_account { get; set; }
        public long practice_code { get; set; }
        public Nullable<long> new_provider { get; set; }
        public string new_provider_name { get; set; }
        public string paid_proc_code { get; set; }
        public string payment_source { get; set; }
        public Nullable<System.DateTimeOffset> date_entry { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public string close_date { get; set; }
    }
}
