//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTH_END_AGING
    {
        public string PRAC_NAME { get; set; }
        public decimal AGING_0_30 { get; set; }
        public decimal AGING_31_60 { get; set; }
        public decimal AGING_61_90 { get; set; }
        public decimal AGING_91_120 { get; set; }
        public decimal AGING_120_PLUS { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<int> CLOSE_MONTH { get; set; }
        public Nullable<int> CLOSE_YEAR { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public long PRACTICE_CODE { get; set; }
    }
}
