//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTH_END_FINANCIAL
    {
        public Nullable<long> PRACTICE_CODE { get; set; }
        public Nullable<decimal> CHARGES { get; set; }
        public Nullable<decimal> ADJUSTMENTS { get; set; }
        public Nullable<decimal> PAYMENTS { get; set; }
        public string CLOSE_DATE { get; set; }
    }
}
