//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTH_END_FINANCIAL_PROVIDE_LOCATION
    {
        public string CLOSE_DATE { get; set; }
        public long PRACTICE_CODE { get; set; }
        public string PRAC_NAME { get; set; }
        public long PROVIDER_CODE { get; set; }
        public long LOCATION_CODE { get; set; }
        public string LOCATION_NAME { get; set; }
        public decimal CHARGES { get; set; }
        public decimal ADJUSTMENTS { get; set; }
        public decimal PAYMENTS { get; set; }
    }
}
