//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_Codes
    {
        public string Codes { get; set; }
        public string Description { get; set; }
        public System.DateTime Effective_Date { get; set; }
        public string Short_Desscripton_not_more_than_255 { get; set; }
    }
}
