//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operating_Test
    {
        public int id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<long> practice_code { get; set; }
        public Nullable<long> claim_no { get; set; }
        public string NPI { get; set; }
    }
}
