//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packet277CA_Data
    {
        public int id { get; set; }
        public Nullable<int> FileID { get; set; }
        public string ControlHeader_ISA { get; set; }
        public string ControlHeader_ISA01 { get; set; }
        public string ControlHeader_ISA02 { get; set; }
        public string ControlHeader_ISA03 { get; set; }
        public string ControlHeader_ISA04 { get; set; }
        public string ControlHeader_ISA05 { get; set; }
        public string ControlHeader_ISA06 { get; set; }
        public string ControlHeader_ISA07 { get; set; }
        public string ControlHeader_ISA08 { get; set; }
        public Nullable<System.DateTime> ControlHeader_ISA09 { get; set; }
        public string ControlHeader_ISA10 { get; set; }
        public string ControlHeader_ISA11 { get; set; }
        public string ControlHeader_ISA12 { get; set; }
        public string ControlHeader_ISA13 { get; set; }
        public string ControlHeader_ISA14 { get; set; }
        public string ControlHeader_ISA15 { get; set; }
        public string ControlHeader_ISA16 { get; set; }
        public string GroupHeader_GS { get; set; }
        public string GroupHeader_GS01 { get; set; }
        public string GroupHeader_GS02 { get; set; }
        public string GroupHeader_GS03 { get; set; }
        public Nullable<System.DateTime> GroupHeader_GS04 { get; set; }
        public string GroupHeader_GS05 { get; set; }
        public string GroupHeader_GS06 { get; set; }
        public string GroupHeader_GS07 { get; set; }
        public string GroupHeader_GS08 { get; set; }
        public string GroupTrailer_GE { get; set; }
        public string GroupTrailer_GE01 { get; set; }
        public string GroupTrailer_GE02 { get; set; }
        public string ControlTrailer_IEA { get; set; }
        public string ControlTrailer_IEA01 { get; set; }
        public string ControlTrailer_IEA02 { get; set; }
    }
}
