//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packet999_Data
    {
        public int id { get; set; }
        public Nullable<int> FileID { get; set; }
        public string ControlHeader_ISA { get; set; }
        public string ControlHeader_ISA01 { get; set; }
        public string ControlHeader_ISA02 { get; set; }
        public string ControlHeader_ISA03 { get; set; }
        public string ControlHeader_ISA04 { get; set; }
        public string ControlHeader_ISA05 { get; set; }
        public string ControlHeader_ISA06 { get; set; }
        public string ControlHeader_ISA07 { get; set; }
        public string ControlHeader_ISA08 { get; set; }
        public Nullable<System.DateTime> ControlHeader_ISA09 { get; set; }
        public string ControlHeader_ISA10 { get; set; }
        public string ControlHeader_ISA11 { get; set; }
        public string ControlHeader_ISA12 { get; set; }
        public string ControlHeader_ISA13 { get; set; }
        public string ControlHeader_ISA14 { get; set; }
        public string ControlHeader_ISA15 { get; set; }
        public string ControlHeader_ISA16 { get; set; }
        public string GroupHeader_GS { get; set; }
        public string GroupHeader_GS01 { get; set; }
        public string GroupHeader_GS02 { get; set; }
        public string GroupHeader_GS03 { get; set; }
        public Nullable<System.DateTime> GroupHeader_GS04 { get; set; }
        public string GroupHeader_GS05 { get; set; }
        public string GroupHeader_GS06 { get; set; }
        public string GroupHeader_GS07 { get; set; }
        public string GroupHeader_GS08 { get; set; }
        public string TSetHeader_ST { get; set; }
        public string TSetHeader_ST01 { get; set; }
        public string TSetHeader_ST02 { get; set; }
        public string TSetHeader_ST03 { get; set; }
        public string FunctionalResponseHeader_AK1 { get; set; }
        public string FunctionalResponseHeader_AK101 { get; set; }
        public string FunctionalResponseHeader_AK102 { get; set; }
        public string FunctionalResponseHeader_AK103 { get; set; }
        public string FunctionalResponseHeader_AK2 { get; set; }
        public string FunctionalResponseHeader_AK201 { get; set; }
        public string FunctionalResponseHeader_AK202 { get; set; }
        public string FunctionalResponseHeader_AK203 { get; set; }
        public string FunctionalResponseHeader_IK3 { get; set; }
        public string FunctionalResponseHeader_IK301 { get; set; }
        public string FunctionalResponseHeader_IK302 { get; set; }
        public string FunctionalResponseHeader_IK303 { get; set; }
        public string FunctionalResponseHeader_IK304 { get; set; }
        public string FunctionalResponseHeader_CTX1 { get; set; }
        public string FunctionalResponseHeader_CTX101 { get; set; }
        public string FunctionalResponseHeader_CTX102 { get; set; }
        public string FunctionalResponseHeader_CTX103 { get; set; }
        public string FunctionalResponseHeader_CTX104 { get; set; }
        public string FunctionalResponseHeader_CTX105 { get; set; }
        public string FunctionalResponseHeader_CTX106 { get; set; }
        public string FunctionalResponseHeader_CTX2 { get; set; }
        public string FunctionalResponseHeader_CTX201 { get; set; }
        public string FunctionalResponseHeader_CTX202 { get; set; }
        public string FunctionalResponseHeader_IK4 { get; set; }
        public string FunctionalResponseHeader_IK401 { get; set; }
        public string FunctionalResponseHeader_IK402 { get; set; }
        public string FunctionalResponseHeader_IK403 { get; set; }
        public string FunctionalResponseHeader_IK404 { get; set; }
        public string FunctionalResponseHeader_CTX3 { get; set; }
        public string FunctionalResponseHeader_CTX301 { get; set; }
        public string FunctionalResponseHeader_CTX302 { get; set; }
        public string FunctionalResponseHeader_CTX303 { get; set; }
        public string FunctionalResponseHeader_CTX304 { get; set; }
        public string FunctionalResponseHeader_CTX305 { get; set; }
        public string FunctionalResponseHeader_CTX306 { get; set; }
        public string FunctionalResponseHeader_IK5 { get; set; }
        public string FunctionalResponseHeader_IK501 { get; set; }
        public string FunctionalResponseHeader_IK502 { get; set; }
        public string FunctionalResponseHeader_IK503 { get; set; }
        public string FunctionalResponseHeader_IK504 { get; set; }
        public string FunctionalResponseHeader_IK505 { get; set; }
        public string FunctionalResponseHeader_IK506 { get; set; }
        public string FunctionalResponseHeader_AK9 { get; set; }
        public string FunctionalResponseHeader_AK901 { get; set; }
        public string FunctionalResponseHeader_AK902 { get; set; }
        public string FunctionalResponseHeader_AK903 { get; set; }
        public string FunctionalResponseHeader_AK904 { get; set; }
        public string FunctionalResponseHeader_AK905 { get; set; }
        public string FunctionalResponseHeader_AK906 { get; set; }
        public string FunctionalResponseHeader_AK907 { get; set; }
        public string FunctionalResponseHeader_AK908 { get; set; }
        public string FunctionalResponseHeader_AK909 { get; set; }
        public string Footer_SE { get; set; }
        public string Footer_SE01 { get; set; }
        public string Footer_SE02 { get; set; }
        public string GTFooter_GE { get; set; }
        public string GTFooter_GE01 { get; set; }
        public string GTFooter_GE02 { get; set; }
        public string GTFooter_IEA { get; set; }
        public string GTFooter_IEA01 { get; set; }
        public string GTFooter_IEA02 { get; set; }
        public string Linking_Status { get; set; }
        public string F_Group_RejectionCode999_Message { get; set; }
        public string T_Set_RejectionCode999_Message { get; set; }
        public Nullable<long> batch_id { get; set; }
    }
}
