//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packet277CAClaims
    {
        public int id { get; set; }
        public Nullable<int> Header_id { get; set; }
        public string TSetHeader_ST { get; set; }
        public string TSetHeader_ST01 { get; set; }
        public string TSetHeader_ST02 { get; set; }
        public string TSetHeader_ST03 { get; set; }
        public string BHierarchiTransaction_BHT { get; set; }
        public string BHierarchiTransaction_BHT01 { get; set; }
        public string BHierarchiTransaction_BHT02 { get; set; }
        public string BHierarchiTransaction_BHT03 { get; set; }
        public Nullable<System.DateTime> BHierarchiTransaction_BHT04 { get; set; }
        public string BHierarchiTransaction_BHT05 { get; set; }
        public string BHierarchiTransaction_BHT06 { get; set; }
        public string SourceLevel_HL { get; set; }
        public string SourceLevel_HL01 { get; set; }
        public string SourceLevel_HL02 { get; set; }
        public string SourceLevel_HL03 { get; set; }
        public string SourceLevel_HL04 { get; set; }
        public string SourceName_NM1 { get; set; }
        public string SourceName_NM101 { get; set; }
        public string SourceName_NM102 { get; set; }
        public string SourceName_NM103 { get; set; }
        public string SourceName_NM104 { get; set; }
        public string SourceName_NM105 { get; set; }
        public string SourceName_NM106 { get; set; }
        public string SourceName_NM107 { get; set; }
        public string SourceName_NM108 { get; set; }
        public string SourceName_NM109 { get; set; }
        public string TR_Control_Id_TRN { get; set; }
        public string TR_Control_Id_TRN01 { get; set; }
        public string TR_Control_Id_TRN02 { get; set; }
        public string TR_Control_Id_DTP { get; set; }
        public string TR_Control_Id_DTP01 { get; set; }
        public string TR_Control_Id_DTP02 { get; set; }
        public Nullable<System.DateTime> TR_Control_Id_DTP03 { get; set; }
        public string TR_Control_Id_DTP2 { get; set; }
        public string TR_Control_Id_DTP201 { get; set; }
        public string TR_Control_Id_DTP202 { get; set; }
        public Nullable<System.DateTime> TR_Control_Id_DTP203 { get; set; }
        public string ReceiverLevelHL { get; set; }
        public string ReceiverLevelHL01 { get; set; }
        public string ReceiverLevelHL02 { get; set; }
        public string ReceiverLevelHL03 { get; set; }
        public string ReceiverLevelHL04 { get; set; }
        public string ReceiverName_NM1 { get; set; }
        public string ReceiverName_NM101 { get; set; }
        public string ReceiverName_NM102 { get; set; }
        public string ReceiverName_NM103 { get; set; }
        public string ReceiverName_NM104 { get; set; }
        public string ReceiverName_NM105 { get; set; }
        public string ReceiverName_NM106 { get; set; }
        public string ReceiverName_NM107 { get; set; }
        public string ReceiverName_NM108 { get; set; }
        public string ReceiverName_NM109 { get; set; }
        public string IReciever_AppTransectionID { get; set; }
        public string IReciever_AppTransectionID01 { get; set; }
        public string IReciever_AppTransectionID02 { get; set; }
        public string IReciever_AppSTC { get; set; }
        public string IReciever_AppSTC01_1 { get; set; }
        public string IReciever_AppSTC01_2 { get; set; }
        public string IReciever_AppSTC01_3 { get; set; }
        public string IReciever_AppSTC01_4 { get; set; }
        public Nullable<System.DateTime> IReciever_AppSTC02 { get; set; }
        public string IReciever_AppSTC03 { get; set; }
        public string IReciever_AppSTC04 { get; set; }
        public string IReciever_AppQTY { get; set; }
        public string IReciever_AppQTY01 { get; set; }
        public string IReciever_AppQTY02 { get; set; }
        public string IReciever_AppAMT { get; set; }
        public string IReciever_AppAMT01 { get; set; }
        public string IReciever_AppAMT02 { get; set; }
        public string BP_ServiceLevel { get; set; }
        public string BP_ServiceLevel01 { get; set; }
        public string BP_ServiceLevel02 { get; set; }
        public string BP_ServiceLevel03 { get; set; }
        public string BP_ServiceLevel04 { get; set; }
        public string ProviderName_NM1 { get; set; }
        public string ProviderName_NM101 { get; set; }
        public string ProviderName_NM102 { get; set; }
        public string ProviderName_NM103 { get; set; }
        public string ProviderName_NM104 { get; set; }
        public string ProviderName_NM105 { get; set; }
        public string ProviderName_NM106 { get; set; }
        public string ProviderName_NM107 { get; set; }
        public string ProviderName_NM108 { get; set; }
        public string ProviderName_NM109 { get; set; }
        public string PS_ITID_TRN { get; set; }
        public string PS_ITID_TRN01 { get; set; }
        public string PS_ITID_TRN02 { get; set; }
        public string Provider_STC { get; set; }
        public string Provider_STC01_1 { get; set; }
        public string Provider_STC01_2 { get; set; }
        public string Provider_STC01_3 { get; set; }
        public string Provider_STC01_4 { get; set; }
        public Nullable<System.DateTime> Provider_STC02 { get; set; }
        public string Provider_STC03 { get; set; }
        public string Provider_STC04 { get; set; }
        public string Provider_REF { get; set; }
        public string Provider_REF01 { get; set; }
        public string Provider_REF02 { get; set; }
        public string Provider_QTY { get; set; }
        public string Provider_QTY01 { get; set; }
        public string Provider_QTY02 { get; set; }
        public string Provider_AMT { get; set; }
        public string Provider_AMT01 { get; set; }
        public string Provider_AMT02 { get; set; }
        public string status_code { get; set; }
    }
}
