//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacketFileVitals_Tets1
    {
        public int id { get; set; }
        public string file_name { get; set; }
        public string file_path { get; set; }
        public Nullable<int> total_parsed { get; set; }
        public Nullable<int> total_failed { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> parsing_date_time { get; set; }
    }
}
