//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel_Billing_Code_Cptdetail
    {
        public long Panel_Billing_Code_CPTId { get; set; }
        public long PanelBillingCodeId { get; set; }
        public string Cpt_Code { get; set; }
        public string Cpt_Description { get; set; }
        public string M_1 { get; set; }
        public string M_2 { get; set; }
        public string M_3 { get; set; }
        public string M_4 { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Pos { get; set; }
        public string Alternate_Code { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public Nullable<int> Units { get; set; }
    }
}
