//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATIENT_35510209
    {
        public string Patient_Account { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string MI { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string GENDER { get; set; }
        public int Marital_Status { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZIP { get; set; }
        public string Home_Phone { get; set; }
        public string Business_Phone { get; set; }
        public int Gurantor_Relation { get; set; }
        public string Email_Address { get; set; }
        public int Location_Code { get; set; }
        public Nullable<double> Chart_Id { get; set; }
        public int Practice_Code { get; set; }
        public int Created_By { get; set; }
        public System.DateTimeOffset Created_Date { get; set; }
        public int Deleted { get; set; }
        public int PTL_STATUS { get; set; }
        public int Provider_Code { get; set; }
        public string Cell_Phone { get; set; }
        public int Ethnicities { get; set; }
        public int Race { get; set; }
        public int Languages { get; set; }
        public int IsDeceased { get; set; }
        public int Address_Type { get; set; }
    }
}
