//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients_Data
    {
        public int id { get; set; }
        public Nullable<int> ST_Reference_ID { get; set; }
        public string ST02 { get; set; }
        public string PatientLevel { get; set; }
        public string PatientLevel01 { get; set; }
        public string PatientLevel02 { get; set; }
        public string PatientLevel03 { get; set; }
        public string PatientLevel04 { get; set; }
        public string PatientName_NM1 { get; set; }
        public string PatientName_NM101 { get; set; }
        public string PatientName_NM102 { get; set; }
        public string PatientName_NM103 { get; set; }
        public string PatientName_NM104 { get; set; }
        public string PatientName_NM105 { get; set; }
        public string PatientName_NM106 { get; set; }
        public string PatientName_NM107 { get; set; }
        public string PatientName_NM108 { get; set; }
        public string PatientName_NM109 { get; set; }
        public string CS_ITID_TRN { get; set; }
        public string CS_ITID_TRN01 { get; set; }
        public string CS_ITID_TRN02 { get; set; }
        public string CS_STC { get; set; }
        public string CS_STC01_1 { get; set; }
        public string CS_STC01_2 { get; set; }
        public string CS_STC01_3 { get; set; }
        public string CS_STC01_4 { get; set; }
        public Nullable<System.DateTime> CS_STC02 { get; set; }
        public string CS_STC03 { get; set; }
        public string CS_STC04 { get; set; }
        public string CS_STC05 { get; set; }
        public string CS_STC06 { get; set; }
        public string CS_STC07 { get; set; }
        public string CS_STC08 { get; set; }
        public string CS_STC09 { get; set; }
        public string CS_STC10 { get; set; }
        public string CS_STC11 { get; set; }
        public string CS_STC12 { get; set; }
        public string CS_REF { get; set; }
        public string CS_REF01 { get; set; }
        public string CS_REF02 { get; set; }
        public string CS_DTP { get; set; }
        public string CS_DTP01 { get; set; }
        public string CS_DTP02 { get; set; }
        public Nullable<System.DateTime> CS_DTP03RD8_ToDate { get; set; }
        public Nullable<System.DateTime> CS_DTP03RD8_FromDate { get; set; }
        public string CS_ITID_TRN2 { get; set; }
        public string CS_ITID_TRN201 { get; set; }
        public string CS_ITID_TRN202 { get; set; }
        public string CS_STC2 { get; set; }
        public string CS_STC201_1 { get; set; }
        public string CS_STC201_2 { get; set; }
        public string CS_STC201_3 { get; set; }
        public string CS_STC201_4 { get; set; }
        public Nullable<System.DateTime> CS_STC202 { get; set; }
        public string CS_STC203 { get; set; }
        public string CS_STC204 { get; set; }
        public string CS_STC205 { get; set; }
        public string CS_STC206 { get; set; }
        public string CS_STC207 { get; set; }
        public string CS_STC208 { get; set; }
        public string CS_STC209 { get; set; }
        public string CS_STC210 { get; set; }
        public string CS_STC211 { get; set; }
        public string CS_STC212 { get; set; }
        public string CS_REF2 { get; set; }
        public string CS_REF201 { get; set; }
        public string CS_REF202 { get; set; }
        public string CS_DTP2 { get; set; }
        public string CS_DTP201 { get; set; }
        public string CS_DTP202 { get; set; }
        public Nullable<System.DateTime> CS_DTP203RD8_ToDate { get; set; }
        public Nullable<System.DateTime> CS_DTP203RD8_FromDate { get; set; }
        public string CS_ITID_TRN3 { get; set; }
        public string CS_ITID_TRN301 { get; set; }
        public string CS_ITID_TRN302 { get; set; }
        public string CS_STC3 { get; set; }
        public string CS_STC301_1 { get; set; }
        public string CS_STC301_2 { get; set; }
        public string CS_STC301_3 { get; set; }
        public string CS_STC301_4 { get; set; }
        public Nullable<System.DateTime> CS_STC302 { get; set; }
        public string CS_STC303 { get; set; }
        public string CS_STC304 { get; set; }
        public string CS_STC305 { get; set; }
        public string CS_STC306 { get; set; }
        public string CS_STC307 { get; set; }
        public string CS_STC308 { get; set; }
        public string CS_STC309 { get; set; }
        public string CS_STC310 { get; set; }
        public string CS_STC311 { get; set; }
        public string CS_STC312 { get; set; }
        public string CS_REF3 { get; set; }
        public string CS_REF301 { get; set; }
        public string CS_REF302 { get; set; }
        public string CS_QTY { get; set; }
        public string CS_QTY01 { get; set; }
        public string CS_QTY02 { get; set; }
        public string CS_AMT { get; set; }
        public string CS_AMT01 { get; set; }
        public string CS_AMT02 { get; set; }
        public string CS_DTP3 { get; set; }
        public string CS_DTP301 { get; set; }
        public string CS_DTP302 { get; set; }
        public Nullable<System.DateTime> CS_DTP303RD8_ToDate { get; set; }
        public Nullable<System.DateTime> CS_DTP303RD8_FromDate { get; set; }
        public string CS_SE { get; set; }
        public string CS_SE01 { get; set; }
        public string CS_SE02 { get; set; }
        public string Claim { get; set; }
        public string Practise_Code { get; set; }
        public string Linking_Status { get; set; }
        public string Status { get; set; }
        public string Claim_Status_Category_Code { get; set; }
        public string Claim_Status_Code { get; set; }
        public string Entity_Identifier_Code { get; set; }
    }
}
