//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient_statement_itemized_tets_bkp
    {
        public long S_NO { get; set; }
        public Nullable<long> PATIENT_ACCOUNT { get; set; }
        public long CLAIM_NO { get; set; }
        public Nullable<System.DateTime> DATE1 { get; set; }
        public string PROC_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<long> PRACTICE_CODE { get; set; }
        public Nullable<System.DateTime> PROCESS_DATE { get; set; }
        public Nullable<decimal> REJECT_AMT { get; set; }
        public Nullable<System.DateTime> CUT_OF_DATE { get; set; }
        public Nullable<int> pages { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<decimal> Pat_Amount { get; set; }
        public Nullable<decimal> Ins_Amount { get; set; }
    }
}
