//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice_Reporting
    {
        public long ID { get; set; }
        public long Practice_Code { get; set; }
        public string Practice_Alias { get; set; }
        public Nullable<long> Manager_ID { get; set; }
        public Nullable<long> TeamLead_ID { get; set; }
        public Nullable<long> BillingAssociate_ID { get; set; }
        public string Shift { get; set; }
        public Nullable<long> User_ID { get; set; }
        public Nullable<long> Division_ID { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<long> PHD_POCid { get; set; }
    }
}
