//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Prod_Id { get; set; }
        public Nullable<long> Cat_id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<long> Unit_Price { get; set; }
        public Nullable<System.DateTime> Manf_Date { get; set; }
        public Nullable<System.DateTime> Exp_Date { get; set; }
        public Nullable<long> Total_Items { get; set; }
    }
}
