//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sampledata
    {
        public string Date { get; set; }
        public double Current_A_R { get; set; }
        public short Year { get; set; }
        public int Practice_code { get; set; }
        public byte month { get; set; }
    }
}
