//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sample_data
    {
        public long id { get; set; }
        public Nullable<long> Practice_code { get; set; }
        public Nullable<decimal> Total_current_AR { get; set; }
        public Nullable<System.DateTime> Date_Freeze { get; set; }
        public Nullable<long> Month { get; set; }
        public Nullable<long> Years { get; set; }
    }
}
