//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrcubber
    {
        public int Id { get; set; }
        public string PracticeCode { get; set; }
        public string PracticeName { get; set; }
        public Nullable<System.DateTime> RejectionDate { get; set; }
        public string AccountNumber { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> ClaimNumber { get; set; }
        public Nullable<System.DateTime> DateOfService { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public string RejectionReason { get; set; }
        public string Status { get; set; }
    }
}
