using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace NPMAPI.Models
{
    public class SPDataModel
    {
        public string claim_no { get; set; }
        public string sequence_no { get; set; }
        public string clm1 { get; set; }
        public string SecInsName { get; set; }
        public string SPatient_Account { get; set; }
        public DateTime PISSubscriber { get; set; }
        public string SecPolicyNo { get; set; }
        public string Notes { get; set; }
        public DateTime Injury_Date { get; set; }
        public bool Accident_Auto { get; set; }
        public int? Employment { get; set; }
        public string Accident_State { get; set; }
        public bool Accident_Other { get; set; }
        public string SSubscriber { get; set; }
        public string SDOB { get; set; }
        public string SSex { get; set; }
        public string InType { get; set; }
        public string PriInsurance { get; set; }
        public string MEDICARE_NO { get; set; }
        public string MEDICARE_GRP_NO { get; set; }
        public string PRAC_ADDRESS { get; set; }
        public string PROVID_ADDRESS { get; set; }
        public string PRAC_NAME { get; set; }
        public string EMR_NAME { get; set; }
        public string PRAC_TAX_ID { get; set; }
        public string PRAC_TAX_ID_SSN_OR_EIN { get; set; }
        public string CARRIER_CODE { get; set; }
        public string PROVIDER_CODE { get; set; }
        public string PRACTICE_CODE { get; set; }
        public string PROVIDER_NAME { get; set; }
        public string PHONE_One { get; set; }
        public string PROVID_UPIN { get; set; }
        public string PROVID_STATE_LICENSE { get; set; }
        public string PROVID_FNAME { get; set; }
        public string PROVID_MNAME { get; set; }
        public string PROVID_LNAME { get; set; }
        public string Taxonomy_Code { get; set; }
        public string clm { get; set; }
        public long Pat_Acc { get; set; }
        public DateTime current_illness_date { get; set; }
        public DateTime x_ray_date { get; set; }
        public string Reference_Number { get; set; }
        public DateTimeOffset BILL_DATE { get; set; }
        public long REFerring_PHYSICIAN { get; set; }
        public long billing_physician { get; set; }
        public long ATTending_PHYSICIAN { get; set; }
        public long FACILITY_CODE { get; set; }
        public DateTime HOSPital_FROM { get; set; }
        public DateTime HOSPital_TO { get; set; }
        public string DX_CODE1 { get; set; }
        public string DX_CODE2 { get; set; }
        public string DX_CODE3 { get; set; }
        public string DX_CODE4 { get; set; }
        public string DX_CODE5 { get; set; }
        public string DX_CODE6 { get; set; }
        public string DX_CODE7 { get; set; }
        public string DX_CODE8 { get; set; }
        public string DX_CODE9 { get; set; }
        public string DX_CODE10 { get; set; }
        public string DX_CODE11 { get; set; }
        public string DX_CODE12 { get; set; }
        public string ICD_INDICATOR { get; set; }
        //public bool Accident_Auto { get; set; }
        //public bool Accident_Other { get; set; }
        //public bool? Employment { get; set; }
        public DateTime ACCIDent_DATE { get; set; }
        public DateTime lmp_date { get; set; }
        //public string Accident_State { get; set; }
        public string PA_NUMBER { get; set; }
        public string REFERRAL_NUMBER { get; set; }
        public int AA { get; set; }
        public string BLOCK1213 { get; set; }
        public bool Accident_Emergency { get; set; }
        public long LOCATION_CODE { get; set; }
        public decimal CLAIM_TOTAL { get; set; }
        public decimal AMT_PAID { get; set; }
        public decimal AMT_DUE { get; set; }
        public decimal PATient_Payment { get; set; }
        public long PATIENT_ACCOUNT { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIddle_name { get; set; }
        public string Gender { get; set; }
        public DateTime birth_DATE { get; set; }
        public int Marital_Status { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string HOME_PHONE { get; set; }
        public string EMPLOYMENT_TYPE { get; set; }
        public string EMPLOYER_CODE { get; set; }
        public string SSN { get; set; }
        public string PROCEDURE_CODE { get; set; }
        public DateTime DOE { get; set; }
        public DateTime DOS_FROM { get; set; }
        public DateTime DOS_TO { get; set; }
        public int DX_pointer1 { get; set; }
        public int DX_pointer2 { get; set; }
        public int DX_pointer3 { get; set; }
        public int DX_pointer4 { get; set; }
        public string MODI_CODE1 { get; set; }
        public string MODI_CODE2 { get; set; }
        public int UNITS { get; set; }
        public decimal AMOUNT { get; set; }
        public int seq { get; set; }
        public string Proc_Description { get; set; }
        public bool Corrected_Claim { get; set; }
        public string ICN { get; set; }
        public DateTime start_time { get; set; }
        public DateTime stop_time { get; set; }
        public string MODI_CODE3 { get; set; }
        public string MODI_CODE4 { get; set; }
        public string drug_code { get; set; }
        public string POLICY_NUMBER { get; set; }
        public string GROUP_NUMBER { get; set; }
        public long SUBSCRIBER { get; set; }
        public string RELATIONSHIP { get; set; }
        public DateTime EFFECTIVE_DATE { get; set; }
        public DateTime TERMINATION_DATE { get; set; }
        public string PRI_SEC_OTH_TYPE { get; set; }
        public decimal DEDUCTIONS { get; set; }
        public int POS { get; set; }
        public long INSURANCE_CODE { get; set; }
        public string INSURANCE_ADDRESS { get; set; }
        public string INSURANCE_CITY { get; set; }
        public string INSURANCE_STATE { get; set; }
        public string INSURANCE_ZIP { get; set; }
        public long INSPayer_Id { get; set; }
        public string INSPayer_Description { get; set; }
        public long insname_id { get; set; }
        public string INSPayer_837_Id { get; set; }
        public string INSNAME_DESCRIPTION { get; set; }
        public string INSURANCE_TYPE_CODE { get; set; }
        public string s_no { get; set; }
        public long InsGroup_Id { get; set; }
        public string Revenue_Code { get; set; }
        public string Revenue_Description { get; set; }
        public string insgroup_name { get; set; }
        public string PROVIDER_Payer_Id { get; set; }
        public string Group_Suffix { get; set; }
        public string PINGROUP { get; set; }
        public string PINADDRESS { get; set; }
        public string PINADD { get; set; }
        public string PINTAXID { get; set; }
        public string PIN_E_S { get; set; }
        public long LC { get; set; }
        public string PROVID_NPI { get; set; }
        public string Prac_Type { get; set; }
        public string practice_NPI { get; set; }
        public string clia_number { get; set; }
        public long referral_code { get; set; }
        public string REFERRAL_NPI { get; set; }
        public string referral_lname { get; set; }
        public string referral_fname { get; set; }
        public string referral_upin { get; set; }
        public string pin { get; set; }
        public string REFERRAL_LICENSE { get; set; }
        public string REFERRAL_TAX_ID { get; set; }
        public string referral_mi { get; set; }
        public string referral_state { get; set; }
        public string FACILITY_NAME { get; set; }
        public string FACILITY_NPI { get; set; }
        public string FACILITY_ADDRESS { get; set; }
        public string FACILITY_CITY { get; set; }
        public string FACILITY_STATE { get; set; }
        public string FACILITY_ZIP { get; set; }
        public string FACILITY_CONTACT_NAME { get; set; }
        public string FACILITY_ID_NUMBER { get; set; }
        public string FACILITY_PHONE { get; set; }
        public string FACILITY_TYPE { get; set; }
        public long GUARANTOR_CODE { get; set; }
        public string GUARANT_LNAME { get; set; }
        public string GUARANT_FNAME { get; set; }
        public string GUARANT_MI { get; set; }
        public string GUARANT_HOME_PHONE { get; set; }
        public string GUARANT_Work_PHONE { get; set; }
        public string GUARANT_Work_PHONE_EXT { get; set; }
        public string GUARANT_ADDRESS { get; set; }
        public string GUARANT_CITY { get; set; }
        public string GUARANT_STATE { get; set; }
        public string GUARANT_ZIP { get; set; }
        public DateTime GUARANT_DOB { get; set; }
        public string GUARANT_Gender { get; set; }
        public string GUARANT_EMPLOYER_CODE { get; set; }
        public string LOCATION_NAME { get; set; }
        public string LOCATION_ADDRESS { get; set; }
        public string LOCATIONADDCITY { get; set; }
        public string LOCATIONADDSTATE { get; set; }
        public string LOCATIONADDZIP { get; set; }
        public string LOCATIONADDNPI { get; set; }
        public string EMPLOYER_NAME { get; set; }
        public string supervising_physician_fname { get; set; }
        public string supervising_physician_lname { get; set; }
        public string supervising_physician_UPIN { get; set; }
        public string Dischargehour { get; set; }
        public string Admhour { get; set; }
        public int Type_Of_Admission_Id { get; set; }
        public int Type_of_Bill { get; set; }
        public string AdmSource { get; set; }
        public string Discharge_status_Id { get; set; }
        public string ProviderFNamer { get; set; }
        public string ProviderMNamer { get; set; }
        public string ProviderLNamer { get; set; }
        public string ProviderNpi { get; set; }
    }
}