//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_data_dump_cpt
    {
        public short ID { get; set; }
        public Nullable<int> Procedure { get; set; }
        public Nullable<short> REV_CODE { get; set; }
        public string Description { get; set; }
    }
}
