//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tem1
    {
        public long Claim_No { get; set; }
        public Nullable<System.DateTime> InvoiceDOS { get; set; }
        public string Notes { get; set; }
        public string Service_Code { get; set; }
        public string Description { get; set; }
        public long claim_charges_id { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<decimal> Total_Charge { get; set; }
        public Nullable<decimal> Insurance_Owed_Amount_Cents { get; set; }
        public Nullable<decimal> Covered_Amount { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
