//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public long Ticket_Id { get; set; }
        public Nullable<long> Department_Id { get; set; }
        public string Ticket_Type { get; set; }
        public string Ticket_Reason { get; set; }
        public string Ticket_Priority { get; set; }
        public string Ticket_Title { get; set; }
        public string Ticket_Status { get; set; }
        public Nullable<long> Ticket_Aging { get; set; }
        public string Closing_Remarks { get; set; }
        public Nullable<long> Practice_Code { get; set; }
        public string RProvider_Id { get; set; }
        public string BProvider_Id { get; set; }
        public Nullable<long> Assigned_User { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
