//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Patient_Claims_Info
    {
        public long ID { get; set; }
        public Nullable<long> Ticket_Id { get; set; }
        public string Patient_Account { get; set; }
        public string Claim_No { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string MI { get; set; }
        public string PatientCell_Phone { get; set; }
        public string PatientHome_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string SSN { get; set; }
        public Nullable<System.DateTime> DOS { get; set; }
        public Nullable<decimal> Total_Billed { get; set; }
        public Nullable<decimal> Claim_Due { get; set; }
        public Nullable<decimal> Patient_Due { get; set; }
        public string Ins_Mode { get; set; }
        public string Payer_Name { get; set; }
        public string Payer_Id { get; set; }
        public string Policy_No { get; set; }
        public Nullable<long> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Modified_By { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
