//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPMAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transact
    {
        public int srTransact { get; set; }
        public int id { get; set; }
        public int file_id { get; set; }
        public int sec_id { get; set; }
        public int hl_id { get; set; }
        public int segment_type_id { get; set; }
        public string segment_type_value { get; set; }
        public string claim_no { get; set; }
        public string Practice_code { get; set; }
        public string isMatched { get; set; }
        public string statusStc { get; set; }
        public string stc101Message { get; set; }
        public string stc102Message { get; set; }
        public string stc103Message { get; set; }
    }
}
